### ISSUE TITLE
FindStringRef returns nullptr

### ISSUE THREAD

**Issue by MyFedora** [kem0x/Memcury#12]
This issue appears to originate from Memcury. I don't know whether this is related to Memcury itself, or how UnrealMappingsDumper interacts with Memcury. Sorry if this turns out to be unrelated.

### Related issues

- https://github.com/TheNaeem/UnrealMappingsDumper/issues/11
- https://github.com/TheNaeem/UnrealMappingsDumper/issues/20

**Comment by kem0x** [comment]
This issue is not related to memcury, as you see in [UnrealMappingsDumpers's #11](https://github.com/TheNaeem/UnrealMappingsDumper/issues/11) that this got solved by the owner and not on my end.

**Comment by MyFedora** [comment]
@TheNaeem fixed the bug _only locally_, perhaps to their local Memcury repository, but not upstream. [They also contributed various fixes to Memcury in the past](https://github.com/kem0x/Memcury/commits?author=TheNaeem), so this isn't out of the question. Please reopen this issue.

**Comment by Kyiro** [comment]
@MyFedora You can see how that error happens if you look at the code. It's in no way caused by Memcury
https://github.com/kem0x/Memcury/blob/master/memcury.h#L817
